/* 
  Standalone code for querying Nvidia GPU devices. 
  Prints device properties.
  See https://docs.nvidia.com/cuda/cuda-runtime-api/structcudaDeviceProp.html
  for a list of available device properties.

  ! Generated by ChatGPT !
*/

#include <cuda_runtime.h>
#include <iostream>
#include <iomanip>

static void check(cudaError_t err, const char* msg) {
  if (err != cudaSuccess) {
    std::cerr << "CUDA error at " << msg << ": "
              << cudaGetErrorString(err) << std::endl;
    std::exit(EXIT_FAILURE);
  }
}

int main() {
  int deviceCount = 0;
  check(cudaGetDeviceCount(&deviceCount), "cudaGetDeviceCount");

  if (deviceCount == 0) {
    std::cout << "No CUDA devices found.\n";
    return 0;
  }

  std::cout << "Found " << deviceCount << " CUDA device(s)\n\n";

  for (int dev = 0; dev < deviceCount; ++dev) {
    cudaDeviceProp prop{};
    check(cudaGetDeviceProperties(&prop, dev), "cudaGetDeviceProperties");

    std::cout << "========================================\n";
    std::cout << "Device " << dev << ": " << prop.name << "\n";
    std::cout << "========================================\n";

    // Architecture
    std::cout << "Compute capability        : "
              << prop.major << "." << prop.minor << "\n";
    std::cout << "SM count                  : "
              << prop.multiProcessorCount << "\n";

    // Clocks
    std::cout << "Core clock                : "
              << prop.clockRate / 1000 << " MHz\n";
    std::cout << "Memory clock              : "
              << prop.memoryClockRate / 1000 << " MHz\n";
    std::cout << "Memory bus width          : "
              << prop.memoryBusWidth << " bits\n";

    // Memory
    std::cout << "Global memory             : "
              << prop.totalGlobalMem / (1024 * 1024) << " MiB\n";
    std::cout << "L2 cache size             : "
              << prop.l2CacheSize << " B\n";
    std::cout << "Shared memory per SM      : "
              << prop.sharedMemPerMultiprocessor << " B\n";
    std::cout << "Shared memory per block   : "
              << prop.sharedMemPerBlock << " B\n";

    // Registers / execution
    std::cout << "Registers per SM          : "
              << prop.regsPerMultiprocessor << "\n";
    std::cout << "Registers per block       : "
              << prop.regsPerBlock << "\n";
    std::cout << "Warp size                 : "
              << prop.warpSize << "\n";
    std::cout << "Max warps per SM          : "
              << prop.maxThreadsPerMultiProcessor / prop.warpSize << "\n";
    std::cout << "Max threads per SM        : "
              << prop.maxThreadsPerMultiProcessor << "\n";
    std::cout << "Max threads per block     : "
              << prop.maxThreadsPerBlock << "\n";

    // Launch limits
    std::cout << "Max blocks per SM         : "
              << prop.maxBlocksPerMultiProcessor << "\n";
    std::cout << "Max grid dims             : "
              << prop.maxGridSize[0] << " x "
              << prop.maxGridSize[1] << " x "
              << prop.maxGridSize[2] << "\n";
    std::cout << "Max block dims            : "
              << prop.maxThreadsDim[0] << " x "
              << prop.maxThreadsDim[1] << " x "
              << prop.maxThreadsDim[2] << "\n";

    // Misc
    std::cout << "Concurrent kernels        : "
              << prop.concurrentKernels << "\n";
    std::cout << "Unified addressing        : "
              << prop.unifiedAddressing << "\n";
    std::cout << "ECC enabled               : "
              << prop.ECCEnabled << "\n";

    std::cout << "\n";
  }

  return 0;
}
